ALTER TABLE `purchaseDetails`
    ADD COLUMN `grossTotal` DECIMAL(14, 4) NULL DEFAULT 0,
    ADD COLUMN `netTotal` DECIMAL(14, 4) NULL DEFAULT 0,
    ADD COLUMN `taxBase` DECIMAL(14, 4) NULL DEFAULT 0,
    ADD COLUMN `tax` DECIMAL(14, 4) NULL DEFAULT 0,
    ADD COLUMN `taxRate` DECIMAL(5, 2) NULL,
    ADD COLUMN `taxType` VARCHAR(20) NULL,
    ADD COLUMN `taxLabel` VARCHAR(50) NULL,
    ADD COLUMN `isTaxable` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `discountAllocation` DECIMAL(14, 4) NULL DEFAULT 0;
